### ISSUE TITLE
Shouldn't action docstring_check.yaml be run an PR ?

### ISSUE THREAD

**Issue by wizmer** [BlueBrain/libsonata#127]
Instead of on push ?

**Comment by mgeplf** [comment]
Could you expand on your thinking?

**Comment by wizmer** [comment]
This check is currently run when the PR is merged so if it fails, it's too late, the PR is already merged.
I'm not sure but I think the intent was to have this check be run as part of the CI PR.
So I think the trigger should be: `pull_request:` and not `push:` in the yml file.
But again, I'm not sure of the initial intent. It is just something I noticed while looking at something else.

**Comment by mgeplf** [comment]
> This check is currently run when the PR is merged so if it fails, it's too late, the PR is already merged.

Won't a push exist before a PR can be created, and then the doc is checked?

**Comment by wizmer** [comment]
The `push:` will be triggered only if you are not making the PR from you own fork but directly from the BlueBrain remote (ie. your workflow). But if someone makes a PR from their own fork, the `push:` event is not triggered.

Click one `view detail` to expand the list of checks for the following PRs:
https://github.com/BlueBrain/libsonata/pull/125 has 5
vs 
https://github.com/BlueBrain/libsonata/pull/126 has 11

**Comment by mgeplf** [comment]
> The push: will be triggered only if you are not making the PR from you own fork

One can enable the github actions, and then it works on your own fork.  The branch protection is enabled, so things shouldn't get merged unless tests pass.

> Click one view detail to expand the list of checks for the following PRs:

Isn't that because the `reports` branch is behind master, and doesn't have the latest CI changes?

I'm looking at all the actions, and they're all 'push'; so this applies to everything, it seems.  When an action is set to PR instead of push, does it get run on each push within the PR?

**Comment by wizmer** [comment]
> When an action is set to PR instead of push, does it get run on each push within the PR?

Yes, that's what happens. If I understand correctly, `pull_requests` should be used to test the PR and `push` to upload the coverage when master branch is updated for example.

**Comment by wizmer** [comment]
Merged in #129
