### ISSUE TITLE
Access report mapping without the need to load a frame

### ISSUE THREAD

**Issue by NadirRoGue** [BlueBrain/libsonata#149]
Hello,

Currently, to access the node compartment mapping, the only option available with the current report reader API is to query a frame of the report and use the ids field of the `DataFrame` object. 

It would be useful to be able to access this mapping information without having to read a full frame, as it might not be needed at the time the mapping is needed.

**Comment by mgeplf** [comment]
@jorblancoa and @alkino implemented the report reading so I think they should look at this.
