### ISSUE TITLE
Filesystem include is missing in external search

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/libsonata#150]
See here:

https://github.com/BlueBrain/libsonata/blob/24f2b18aea5df3ce96089e07de992b3e8507422e/CMakeLists.txt#L68-L75

**Comment by mgeplf** [comment]
Someone else is trying to make a spack package.

I haven't had any luck making it work both in the `EXTLIB_FROM_SUBMODULES` and `find_package(ghc_filesystem)` cases.  I'm very tempted to sidestep the whole issue, and just version it in.

Perhaps we can try and look at it today together.

**Comment by mgeplf** [comment]
@matz-e and I discussed this, and we'll just version in the filesystem compat layer for simplicity.
