### ISSUE TITLE
Aggressive compilation flags

### ISSUE THREAD

**Issue by wizmer** [BlueBrain/libsonata#16]
I am trying to build libsonata wheels however I can't build the package on all the platform because compilation flags are too aggressive.
Here is a warning about narrowing conversion being treated as error on a i686 machine:
https://travis-ci.com/BlueBrain/libsonata-wheels/jobs/196307472#L639

Would you be okay for only enabling these flags in the CI and not by default ? Like in MorphIO: https://github.com/BlueBrain/MorphIO/blob/master/.ContinousIntegration.cmake

**Comment by wizmer** [comment]
@tristan0x Do you have any thought about it ? Do you already have a convention for the activation of Werror ?

Related to: https://github.com/BlueBrain/MorphIO/pull/62

**Comment by tristan0x** [comment]
Sorry for the delay. Somehow this issue passed under my radar.

> Would you be okay for only enabling these flags in the CI and not by default ? Like in MorphIO: https://github.com/BlueBrain/MorphIO/blob/master/.ContinousIntegration.cmake

To prevent a contributor to waste time fixing compilation issues in CI, I think it is important to provide a development environment that is as close as possible as the CI' s.

That being said, I use a CMake option (enabled by default) to activate or not the compilation warnings.
See `${PROJECT_NAME}_CXX_WARNINGS` CMake option below:
https://github.com/BlueBrain/hpc-coding-conventions/blob/master/cpp/cmake/bob.cmake#L192-L255

My suggestion is to turn on the warning's fury by default and disable them when needed.

Cheers

**Comment by wizmer** [comment]
Thanks for your insights @tristan0x 

So following your suggestion I will disable `${PROJECT_NAME}_CXX_WARNINGS` in the `setup.py` so that users that simply want to install the python package don't have to deal with CPP error messages.

Do you have an example of inclusion of bob.cmake within one of your project.

**Comment by wizmer** [comment]
Fixed in https://github.com/BlueBrain/libsonata/pull/19
