### ISSUE TITLE
Funny documentation

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/libsonata#160]
Running `pydoc3 libsonata` I see this, which is not very helpful:
```
Help on package libsonata:

NAME
    libsonata

DESCRIPTION
    # Needed so that mac wheels properly delocate:
    #  https://github.com/matthew-brett/delocate/issues/22

PACKAGE CONTENTS
    _libsonata

DATA
    version = '0.1.8'
```

**Comment by mgeplf** [comment]
Looks like it's taken from: https://github.com/BlueBrain/libsonata/blob/master/python/libsonata/__init__.py

If you can add documentation there, that would be super.
