### ISSUE TITLE
Selection of GIDs get passed as float insted of int

### ISSUE THREAD

**Issue by st4rl3ss** [BlueBrain/libsonata#166]
I noticed that, at least whenever I perform a selection, GIDs get passed as `float` instead of `int` which is weird.
I'm using `flatten()` to create a list of target GIDs.

Feel free to ask for clarifications on this.

**Comment by matz-e** [comment]
Do you have a small reproducer?

**Comment by st4rl3ss** [comment]
Upon further inspection, the problem seems to be unrelated to `libsonata`.
I will check some more but I will close the ticket for now.

Sorry for any inconvenience this might have caused.
