### ISSUE TITLE
Error when installing libsonata with python support

### ISSUE THREAD

**Issue by jorblancoa** [BlueBrain/libsonata#17]
When I am trying to install libsonata through spack with the +python variant 
(-DSONATA_PYTHON=ON) I get an error on pybind11.

This problem was introduced after the last 2 merged PR #15 and #13. If I use the version from the 18th of April everything works fine.

### Steps to reproduce the issue

```console
$ spack install libsonata+python
```
The cmake command that run is:
```
 'cmake' '/gpfs/bbp.cscs.ch/project/proj20/jblanco/spack/var/spack/stage/libsonata-develop-ss6clha6wsjj2xx3pyy2ktzbnn2cv6gu/libsonata' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:PATH=/gpfs/bbp.cscs.ch/project/proj20/jblanco/software/install/linux-rhel7-x86_64/gcc-6.4.0/libsonata-develop-ss6clh' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=FALSE' '-DCMAKE_INSTALL_RPATH:STRING=/gpfs/bbp.cscs.ch/project/proj20/jblanco/software/install/linux-rhel7-x86_64/gcc-6.4.0/libsonata-develop-ss6clh/lib;/gpfs/bbp.cscs.ch/project/proj20/jblanco/software/install/linux-rhel7-x86_64/gcc-6.4.0/libsonata-develop-ss6clh/lib64;/gpfs/bbp.cscs.ch/project/proj20/jblanco/software/install/linux-rhel7-x86_64/gcc-6.4.0/fmt-5.2.1-afhquy/lib64' '-DCMAKE_PREFIX_PATH:STRING=/gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/external-libraries/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-ukuow6gd2f;/gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/tools/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/cmake-3.13.0-ivumccos42;/gpfs/bbp.cscs.ch/project/proj20/jblanco/software/install/linux-rhel7-x86_64/gcc-6.4.0/fmt-5.2.1-afhquy;/gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/external-libraries/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/highfive-2.0-zhmyyjvctj;/gpfs/bbp.cscs.ch/project/proj20/jblanco/software/install/linux-rhel7-x86_64/gcc-6.4.0/py-pybind11-2.2.4-qssapn' '-DEXTLIB_FROM_SUBMODULES=OFF' '-DSONATA_PYTHON=ON' '-DPYTHON_INSTALL_SUFFIX=lib/python3.6/site-packages' '-DPYTHON_EXECUTABLE:FILEPATH=/gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/external-libraries/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-ukuow6gd2f/bin/python3.6'
```

### Error Message
...
-- Configuring done
CMake Error at /p/project/cvsk25/blancoalonso1/HBP/jureca-cluster/29-04-2019/install/linux-centos7-x86_64/gcc-4.8.5/py-pybind11-2.2.4-ld2vao/share/cmake/pybind11/pybind11Tools.cmake:131 (add_library):
  Cannot find source file:
    SYSTEM

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  python/CMakeLists.txt:9 (pybind11_add_module)

CMake Error at /p/project/cvsk25/blancoalonso1/HBP/jureca-cluster/29-04-2019/install/linux-centos7-x86_64/gcc-4.8.5/py-pybind11-2.2.4-ld2vao/share/cmake/pybind11/pybind11Tools.cmake:131 (add_library):
  No SOURCES given to target: sonata_python
Call Stack (most recent call first):
  python/CMakeLists.txt:9 (pybind11_add_module)

**Comment by wizmer** [comment]
Hi,
You need to update your pybind. The SYSTEM keyword was not supported in pybind 2.2.4.

**Comment by jorblancoa** [comment]
@pramodk Could you have a look at this?

**Comment by jorblancoa** [comment]
@wizmer But pybind 2.2.4 is the latest stable version...

**Comment by pramodk** [comment]
@wizmer @arsenius7 : if `pybind 2.2.4` is latest released version, how this should be handled in deployment? Do you guys rely on submodule? In that case could you update Spack libsonata recipe accordingly?

**Comment by mgeplf** [comment]
Doesn' the error look like cmake doesn't support the SYSTEM keyword?

**Comment by wizmer** [comment]
@pramodk I am working on fixing the recipe right now.
@mgeplf No, it is not a problem of cmake but a problem of add_pybind11_module that used to not support passing the SYSTEM keyword.

**Comment by arsenius7** [comment]
https://github.com/BlueBrain/spack/pull/372 should address the issue.
`libsonata` now provides only C++ library (we have removed `python` variant); for Python please use `py-libsonata` instead.
