### ISSUE TITLE
manage manifest in simulation config

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/libsonata#185]
manifest can be added to the simulation config as described here: https://bbpgitlab.epfl.ch/common/doc/circuit-documentation/-/merge_requests/11

libsonata should be updated to follow the specification.

**Comment by jdcourcol** [comment]
@WeinaJi is there any update here ?

**Comment by WeinaJi** [comment]
Hello @jdcourcol , I am just back from my vacation. I will work on it this week.

**Comment by mgeplf** [comment]
closed by #192
