### ISSUE TITLE
should throw an error if biophysical_neuron_models_dir is missing for biophysical nodes

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/libsonata#205]
`it is needed only  for biophysical populations: "Path to the template HOC files defining the E-Model. There must be one defined for biophysical node populations.`

**Comment by joni-herttuainen** [comment]
It seems that the error is not thrown in a case in which the populations dict for a given population is empty.
I.e., Assume components is defined (without `biophysical_neuron_models_dir`) as
```json
"components": {
    "morphologies_dir": "$MORPH_DIR",
}
```

then an error is not thrown for this node population named `default` (that will default to `type = 'biophysical'`)
```json
"populations" : {
    "default": {}
}
```
but is for this:
```json
"populations" : {
    "default": {
        "test": "value"
    }
}
```
This came up in SNAP tests. In the spec it's defined that 
>The dictionary associated to each population may be empty if the components properties don’t need to be overridden
