### ISSUE TITLE
Docs: Missing items in Python API

### ISSUE THREAD

**Issue by joni-herttuainen** [BlueBrain/libsonata#220]
It seems that the [Python API](https://libsonata.readthedocs.io/en/latest/api.html) section in the genereted API docs is missing the following items:
* CircuitConfig
* SimulationConfig
* NodeSets

**Comment by mgeplf** [comment]
@matz-e noticed this as well, I will have a look.

**Comment by mgeplf** [comment]
With the latest release, they are now accessible.
