### ISSUE TITLE
Report.file_name returns full path

### ISSUE THREAD

**Issue by joni-herttuainen** [BlueBrain/libsonata#221]
`libsonata._libsonata.Report.file_name` seems to return the `file_name` as`"$CIRCUIT_DIR/file_name"`. I think this should just be the file name (e.g., `"soma"` or `"soma.h5"` with the added format).

**Comment by mgeplf** [comment]
Quick inspection it's a path that gets concretized to an absolute one, relative to the location of the `simulation_config.json`: do you have the `simulation_config.json` in the same directory as the `circuit_config.json`

**Comment by joni-herttuainen** [comment]
Ah, yes, you're correct. My bad: the description should say `base_path/file_name` where base path is the directory of the simulation.

**Comment by mgeplf** [comment]
nice catch

it appears that the correct behavior from https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md `Reports are always written to the output directory given in the output configuration block`

**Comment by joni-herttuainen** [comment]
Good finding! I seem to always forget such document exists.

**Comment by mgeplf** [comment]
fixed in #222
