### ISSUE TITLE
No population_names when "populations" dict is missing.

### ISSUE THREAD

**Issue by 1uc** [BlueBrain/libsonata#236]
The latest version of `libsonata` seems to no longer report any `population_names` when using a circuit config file which conforms to SONATA spec, but doesn't conform to the BBP-conventions.

Here's the circuit config file:
```
{
  "manifest": { 
    "$BASE_DIR": ".", 
    "$COMPONENT_DIR": "$BASE_DIR", 
    "$NETWORK_DIR": "$BASE_DIR" 
  }, 
  "components": { 
    "morphologies_dir": "$COMPONENT_DIR/ascii_sonata", 
    "biophysical_neuron_models_dir": "not_used" 
  }, 
  "node_sets_file": "not_used", 
  "networks": { 
    "nodes": [ 
      { 
        "nodes_file": "$NETWORK_DIR/nodes.h5", 
        "node_types_file": null 
      } 
    ], 
    "edges": [ 
      { 
        "edges_file": "$NETWORK_DIR/edges_2k.h5", 
        "edge_types_file": null 
      } 
    ] 
  } 
} 
```
When opening this circuit, no population names are reported (from memory):
```
c = libsonata.CircuitConfig.from_file("circuit_config.json")
assert c.population_names == set()
assert c.edge_names == set()
```

Both `nodes.h5` and `edges_2k.h5` contain a single population `"All"`. Note, that doesn't contain a dict `"populations"`, i.e. this is missing:
```
 "edges": [ 
      { 
        ...,
        "populations": { "All": {} }
      } 
```

As far as I understand this is still a conforming file, but it doesn't use BBP conventions.

The question is: Is this change intended?

**Comment by mgeplf** [comment]
> The question is: Is this change intended?

Yes, before we were resolving populations from the node/edge files, but they may contain populations that people don't actually want to access - thus, we now only consider ones that are explicit in the `circuit_config.json`

**Comment by 1uc** [comment]
Thank you!
