### ISSUE TITLE
C++ API documentation not properly displayed

### ISSUE THREAD

**Issue by 1uc** [BlueBrain/libsonata#249]
The C++ API documentation published on readthedocs, e.g.
 https://libsonata.readthedocs.io/en/latest/cpp/doxygen_CircuitConfig.html

doesn't display any useful information, see screenshot.
![2023-02-13-093007_2886x1879_scrot](https://user-images.githubusercontent.com/8473921/218409577-d2ee0144-88b5-4622-ba01-c0cad8dc4f6b.png)

Two other BBPers confirm it's not just a local broswer issue.

**Comment by 1uc** [comment]
There seems to be an "unwrapped" version of the documentation here:
https://libsonata.readthedocs.io/en/latest/cpp/classbbp_1_1sonata_1_1_circuit_config.html

This works well for me.

**Comment by 1uc** [comment]
Possibly related to: https://github.com/BlueBrain/sphinx-bluebrain-theme/issues/66

**Comment by mgeplf** [comment]
Looks like the fix for https://github.com/BlueBrain/sphinx-bluebrain-theme/issues/66 worked:
https://libsonata.readthedocs.io/en/stable/cpp/doxygen_CircuitConfig.html

Can you confirm @1uc?

**Comment by 1uc** [comment]
Thank you! I couldn't spot anything broken.

However, when following a link towards the bottom of a long page such as `SonataError` near the bottom of:
https://libsonata.readthedocs.io/en/stable/cpp/doxygen_CircuitConfig.html

Then if the new page is shorter, I see a blank page until I stroll up. If I then reload the short page, the excess white space at the bottom vanishes.

This works well though. Thanks for fixing this.

**Comment by mgeplf** [comment]
> Then if the new page is shorter, I see a blank page until I stroll up. If I then reload the short page, the excess white space at the bottom vanishes.

Huh, strange, I can't recreate that, but my web knowledge is effectively zero, so there are problably ways to do it.  Glad you can live with it.

> This works well though. Thanks for fixing this.

No problem, thanks for the report.  I'll close this up.
