### ISSUE TITLE
Switch `connection_overrides` in config to be a list

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/libsonata#262]
As per change in specification:
https://github.com/BlueBrain/sonata-extension/pull/24

**Comment by anilbey** [comment]
Hi, I noticed some edge cases fail.

```
"connection_overrides": [],
```

This gives 

```
>       self._libsonata = config_class.from_file(config)                                                                                                                                                   
E       libsonata._libsonata.SonataError: `connection_overrides` must be an array
```

This also fails with the error saying `connection_overrides` must be an array. Perhaps it can give a more accurate error e.g. the fields "source" and "target" need to be present in a connection override.

```
"connection_overrides": [{}],
```

**Comment by mgeplf** [comment]
Weird, I will look into; thanks.

**Comment by anilbey** [comment]
Also "synapse_configure" is not retrieved. Did its name change?

E.g. this gets parsed without the synapse_configure?
```json
    {
      "name": "SC-All",
      "source": "HipProjections",
      "target": "Mosaic",
      "weight": 1.0,
      "spont_minis": 0.2,
      "synapse_configure": "%s.tau_r_NMDA = 3.9 %s.tau_d_NMDA = 148.5"
    },
    ```

**Comment by anilbey** [comment]
Snap retrieves it like this

```python
{'name': 'All-All', 'source': 'Mosaic', 'spont_minis': 0.01, 'target': 'Mosaic', 'weight': 1.0}
```

**Comment by mgeplf** [comment]
> Also "synapse_configure" is not retrieved. Did its name change?

It shouldn't have, could you try an older version of libsonata, and see if it works as expected?

**Comment by anilbey** [comment]
Yes the old version was working as expected for a long time on the CI system.

**Comment by anilbey** [comment]
E.g. on this URL it ran successfully with `libsonata==0.1.18`

`https://PATH_TO_OUR_GITLAB/cells/bglibpy/-/jobs/684478`

**Comment by anilbey** [comment]
Update: synapse_configure was a mistake on my side. It's a false positive.

**Comment by mgeplf** [comment]
I think we're good now; can you test the latest release @anilbey ?

**Comment by anilbey** [comment]
The tests all pass with 0.1.20.

**Comment by mgeplf** [comment]
Excellent, I will close this.  Thanks for testing.
