### ISSUE TITLE
simulation config: no default value for key `input: random_seed`

### ISSUE THREAD

**Issue by WeinaJi** [BlueBrain/libsonata#269]
As discussed in [BBPBGLIB-1025](https://bbpteam.epfl.ch/project/issues/browse/BBPBGLIB-1025), the `random_seed` key of certain stimulus type should not have a default value set from the parser. This key is used to override a gid dependent seed computed internally by neurodamus.  Currently our parser set its default to be the `run:random_seed` which always disables the gid dependent seeding and leads to an anomalous behavior in the simulation.

**Comment by mgeplf** [comment]
Are you looking at other places where this may be the case?  It sounds like we may need to audit the implementation vs the specification, so make sure other things like this aren't missed.

**Comment by WeinaJi** [comment]
Our neurodamus CI has covered most of the parameters that were often used in BlueConfig and migrated to SONATA. While this `random_seed` parameter is used for some of the new stimuli for which the implementations were recently added by scientists in neurodamus, and unfortunately not fully tested for SONATA config in our CI. I will check in neurodamus if we have any other similar new implementation. For new parameters in the future to the SONATA config, we will make sure that 
1) the SONATA spec is clear with the default value
2) sufficient test case in neurodamus

**Comment by mgeplf** [comment]
Thanks for fixing this.
