### ISSUE TITLE
Possibly avoid `using` in public headers.

### ISSUE THREAD

**Issue by 1uc** [BlueBrain/libsonata#301]
We define `H5` to be an alias for the namespace `HighFive` here:
https://github.com/BlueBrain/libsonata/blob/7a3983a4ac89535550075feafd5338a1693a1f5f/include/bbp/sonata/report_reader.h#L13

While libsonata hasn't commited to a stable API yet, IMO it's worth considering removing the line. Especially, since `H5` is mildly encroaching on HDF5 names.

**Comment by mgeplf** [comment]
100% agree; I'll make a PR.

**Comment by mgeplf** [comment]
Fixed in #316
