### ISSUE TITLE
Build failure on Ubuntu 20.04.

### ISSUE THREAD

**Issue by 1uc** [BlueBrain/libsonata#328]
When installing `libhdf5-openmpi-dev` libsonata fails to compile. Having a hard requirement on which variant of the HDF5 library must be installed very quickly leads to conflicts requiring users to un- and re-install HDF5 whenever they switch from working with libsonata and something that uses HDF5 and MPI.

CI has been prepared to expose the issue: #327

**Comment by 1uc** [comment]
Seemingly resolved by using the MPI compiler wrappers as `CC` and `CXX`.

**Comment by mgeplf** [comment]
Approved the CI in #327; hopefully that catches things in the future.
Thanks!
