### ISSUE TITLE
Performances of EdgePopulation::connectingEdges

### ISSUE THREAD

**Issue by tomdele** [BlueBrain/libsonata#35]
We have seen some performance issues using EdgePopulation::connectingEdges. 
This is mainly due to the costly set_intersection function. Finding something else to compute the range intersection could greatly improve the performances.

**Comment by mgeplf** [comment]
I think adding an example of where it's slow would be helpful, so that when we get to this issue in the future, we know where to start.  Please make sure the example is anonymized. 

Do you have benchmarks for where `std::set_intersection` is the bottleneck?

**Comment by tomdele** [comment]
Sorry about that. After some further checks it appears that it is not the set_intersection that is causing problem but `EdgePopulation::afferentEdges` with my data. 
I am closing the issue.
