### ISSUE TITLE
Allow Set Attributes

### ISSUE THREAD

**Issue by KeremKurban** [BlueBrain/libsonata#353]
I am working on publishing a SONATA circuit but bluepysnap validation has requested  a/efferent_section_type (s) for edges file generated with projectionizer's older version. Since we cannot rebuild it , i am working on a script to set attributes per edge. Thought this could be a method in libsonata as older SONATA circuits often requires modifications with latest spec.

Can we have this feature or do you have any other suggestion ?

Thanks

**Comment by mgeplf** [comment]
We can't support writing within libsonata; it's out of the scope of the tool.
Using `h5py` when using python is the best course of action.
