### ISSUE TITLE
Add support for enum datatypes

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/libsonata#36]
See the excellent specification document of [SONATA](https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md#nodes---enum-datatypes) – from the HPC side, we need support for the enum datatypes for circuits, to avoid repeatedly calculating unique values and indices.

I propose to augment the population interface by adding/changing the following methods:
```
    /**
     * Get attribute values for given Selection
     *
     * Enum datatypes will be resolved.
     *
     * @param name is a string to allow attributes not defined in spec
     * @throw if there is no such attribute for the population
     * @throw if the attribute is not defined for _any_ element from the selection
     */
    template <typename T>
    std::vector<T> getAttribute(const std::string& name, const Selection& selection) const;

    /**
     * Get numerical enumation values for Attribute, given Selection
     *
     * @param name is a string to allow attributes not defined in spec
     * @throw if there is no such enum datatype attribute for the population
     * @throw if the attribute is not defined for _any_ element from the selection
     */
    std::vector<std::size_t> getAttributeIndices(const std::string& name, const Selection& selection) const;

    /**
     * Get list of the enumeration values for Attribute, given Selection
     *
     * @param name is a string to allow attributes not defined in spec
     * @throw if there is no such enum datatype attribute for the population
     * @throw if the attribute is not defined for _any_ element from the selection
     */
    std::vector<std::string> getAttributeValues(const std::string& name, const Selection& selection) const;
```

This is a blocker to use `libsonata` in circuit building.

**Comment by mgeplf** [comment]
* `getAttribute` seems to make sense to me, as long as I'm understanding it right: enums will be expanded for the whole selection to the underlying value, with the duplication that involves, correct?

* `getAttributeIndices`: I think that this should have 'Enum' in the name (`getEnumAttributeIndices`?), since it can only be called on enums.  This results in a bit of namespace pollution, but I think it's worthwhile unless we can think of a way of not throwing `if there is no such enum datatype ...`. Furthermore, I think we need a way of getting the fact that the a particular attribute is an enum, or the list of all enum attributes, so that user can decide when to use the `getEnumAttributeIndices`.  

* same point about naming for `getAttributeValues`

**Comment by matz-e** [comment]
>     * `getAttribute` seems to make sense to me, as long as I'm understanding it right: enums will be expanded for the whole selection to the underlying value, with the duplication that involves, correct?

Correct, that is the idea.

>     * `getAttributeIndices`: I think that this should have 'Enum' in the name (`getEnumAttributeIndices`?), since it can only be called on enums.  This results in a bit of namespace pollution, but I think it's worthwhile unless we can think of a way of not throwing `if there is no such enum datatype ...`. Furthermore, I think we need a way of getting the fact that the a particular attribute is an enum, or the list of all enum attributes, so that user can decide when to use the `getEnumAttributeIndices`.

I may be more partial to `getAttributeEnumIndices`? Sounds slightly nicer to me.

To enable user queries, we can provide `attributeEnumNames()`.

**Comment by mgeplf** [comment]
Sure, as long as the name is clear.  `attributeEnumNames` also sounds reasonable.

**Comment by matz-e** [comment]
FWIW, I have some stub implementation already, and can pursue / test this directly in circuit building.
