### ISSUE TITLE
Circuit / simulation config reader

### ISSUE THREAD

**Issue by arsenius7** [BlueBrain/libsonata#4]
Add methods for parsing [circuit](https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md#network_config) and [simulation](https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md#representing-simulations) JSON configs.

**Comment by arsenius7** [comment]
We can take inspiration from [Brion](https://github.com/BlueBrain/Brion/blob/master/brion/circuitConfig.h) implementation.

**Comment by mgeplf** [comment]
The CircuitConfig is implemented in #142.

**Comment by alkino** [comment]
So we can close this issue now. As #142  is merged

**Comment by mgeplf** [comment]
The simulation config portion isn't done yet: #158, so we can't close this.

**Comment by mgeplf** [comment]
#158 is merged, so we can close this.
