### ISSUE TITLE
Remove VERSION file, use tags

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/libsonata#41]
We currently require `setuptools_scm`:

https://github.com/BlueBrain/libsonata/blob/98aa883849c700c369b532a9f4b6bf2a66ea4edc/setup.py#L146

With this¸ we don't need the dependency on the VERSION file any longer, and can just rely on the VCS to provide all necessary info . `setuptools_scm` will add information to Python tarballs to work without a `.git` directory, too.

For the C++ library, we can rely on `python setup.py --version` to get the version. See also here: https://github.com/BlueBrain/MVDTool/blob/master/CMakeLists.txt#L3

Supersedes #34 in a way.

**Comment by mgeplf** [comment]
I created the v0.0.3 tag, so scm_tools should work

**Comment by matz-e** [comment]
> I created the v0.0.3 tag, so scm_tools should work

Thanks! Without tags, in my local execution, it just returned `0.0.0`.

**Comment by mgeplf** [comment]
I *literally* happened to be looking at it at the same time, for some reason the default version I got was `0.1.devblahblahbalh` ... which is odd.
