### ISSUE TITLE
Error importing libsonata on macOS

### ISSUE THREAD

**Issue by haleepfl** [BlueBrain/libsonata#55]
In a fresh virtualenv (macOS 10.14.6, python 3.6), pip installing libsonata succeeds (using a wheel), but it cannot be imported in python due to the version of the hdf5 lib:

```
>>> import libsonata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/hale/Documents/repos/venv/lib/python3.6/site-packages/libsonata.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/lib/libhdf5.101.dylib
  Referenced from: /Users/hale/Documents/repos/venv/lib/python3.6/site-packages/libsonata.cpython-36m-darwin.so
  Reason: image not found
```

hdf5 has been installed with brew and `brew list --versions hdf5` shows `hdf5 1.10.5_1`. The library in `/usr/local/lib/` is `libhdf5.103.dylib` which is obviously not what libsonata is looking for given the above.

How can I pip install libsonata from wheels and have it be functional?

**Comment by mgeplf** [comment]
Unfortunately, I don't know of a way of properly packaging wheels that have inner dependencies like this on macOS.  If you try installing without using the wheel, does it work?  Something like `pip install --no-binary :all: libsonata`

**Comment by haleepfl** [comment]
Both `pip install --no-binary libsonata libsonata` and `pip install git+https://github.com/BlueBrain/libsonata` work fine it seems. Just the outdated version of hdf5 that libsonata is expecting that is causing issues with the wheel.

**Comment by mgeplf** [comment]
We may have to do something like this:
https://github.com/MacPython/h5py-wheels/blob/master/config.sh#L28

**Comment by mgeplf** [comment]
I believe @wizmer has fixed this problem in `morphio`, so we should be able to do the same thing here, time permitting.

**Comment by mgeplf** [comment]
The new release should work properly whether `brew` exists, and whether hdf is installed.  Could you try it @haleepfl?

**Comment by haleepfl** [comment]
@mgeplf No problems importing libsonata in a fresh venv now. I'm checking with my current setup (I have brew and an older hdf installed).

**Comment by mgeplf** [comment]
Sweet.

I think this is fixed.  I'm going to close this - please reopen if it stops working.
