### ISSUE TITLE
Add proper Python representation

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/libsonata#69]
It would be nice if the Python representation of ranges could be more verbose:
```
>>> from libsonata import Selection as S
>>> S((15, 10))
<libsonata.Selection object at 0x7fffdc7c24b0>
```

**Comment by mgeplf** [comment]
Good call.  Suggestions for behavior when it's really long, though?  ie:
`S(np.arange(0, 10000, 2))`

**Comment by matz-e** [comment]
Could we rely on Numpy's representation for that case? That truncates "nicely".

**Comment by mgeplf** [comment]
I don't think so, if there are many ranges, which don't decay to numpy arrays.

We'll probably have to truncate it ourselves.

**Comment by matz-e** [comment]
That's true, forgot that Numpy is just present on the input side. How about arbitrarily picking the first and last 3 elements to always be displayed?
