### ISSUE TITLE
Simulation output reader

### ISSUE THREAD

**Issue by arsenius7** [BlueBrain/libsonata#7]
Add methods for accessing [simulation reports](https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md#simulation-output---reports).

**Comment by arsenius7** [comment]
@hernando, @jplanasc, if you already have SONATA report reader in Brion or somewhere else, let us consider moving it here.

**Comment by jplanasc** [comment]
I believe support for reading SONATA simulation reports has been implemented in Brion from revision c16a694:
https://github.com/BlueBrain/Brion/commits/master

**Comment by mgeplf** [comment]
Added in #71
